apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: app
        image: 586337033275.dkr.ecr.ap-south-1.amazonaws.com/prod/green-app:latest
        ports:
        - containerPort: 3000
